name: Versions

on: pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Close Nick's PRs
      uses: isaiahmoran/enforce-single-pr@v1
      with:
        username: ncipollo
    - name: Close Isaiah's PRs
      uses: isaiahmoran/enforce-single-pr@v1
      with:
        username: isaiahmoran
